### ISSUE TITLE
Regression: ssl.SSLEOFError Unsupported in Micropython After Recent Commit

### ISSUE THREAD

**Issue by ekondayan** [jczic/MicroWebSrv2#100]
The latest changes in commit `40fc58f4222938e6a3fe04488cb4d474a62b6226` have introduced a compatibility issue with Micropython, specifically related to the handling of SSL errors. The ssl module in Micropython does not support ssl.SSLEOFError, which is now referenced in the Microwebsrv2 code.

Possible Solution:
Exception handling on line 666: `except ssl.SSLEOFError :` to be removed and use the general exception handler below

Additional Context:
- Micropython version: All version
- Microwebsrv2 version: since commit `40fc58f4222938e6a3fe04488cb4d474a62b6226`
- Hardware/Platform details: ESP32

I believe addressing this issue is crucial for maintaining Micropython compatibility.

**Comment by jczic** [comment]
Thank you very much @ekondayan!
It should be OK with the commit: [17611da0d87598846b17b0a3363af6c4438961ca](https://github.com/jczic/MicroWebSrv2/commit/17611da0d87598846b17b0a3363af6c4438961ca)

This SSL error can sometimes occur when a large number of SSL requests (attacks) are cut off before they have been fully transmitted.
This does not affect microcontrollers.

**Comment by ekondayan** [comment]
Thank you. It works now.
