### ISSUE TITLE
MicroWebSrv2Exception: Not enough memory to allocate slots.

### ISSUE THREAD

**Issue by kenjichen** [jczic/MicroWebSrv2#11]
Error messages is as below: "not enough memory" . I have used MicroWebSrv  version 1. It never has this problem,, Could you tell me how to avoid not engough memeory problem?  thanks

and the second issue:  MicroWebSrv can not coexist with mqtt

**********************************************************************************
from MicroWebSrv2 import *

       ---------------------------
       - Python pkg MicroWebSrv2 -
       -      version 2.0.3      -
       -     by JC`zic & HC2     -
       ---------------------------

>>> mws = MicroWebSrv2()
>>> mws.StartManaged()
MWS2-INFO> Stops the managed pool.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 221, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 213, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 184, in StartInPool
MicroWebSrv2Exception: Not enough memory to allocate slots.

**Comment by jczic** [comment]
Hi,
You must to configure it first:
https://github.com/jczic/MicroWebSrv2#mws2-setembeddedconfig
(Before StartManaged, call mws. SetEmbeddedConfig() for example)

**Comment by kc-bam** [comment]
Hi,
i have the same problem on esp32 wroom. setting the setembeddedconfig() also didn't help.

**Comment by jczic** [comment]
Hi @kenjichen and @kc-bam,
I think that you doesn't have suffisant memory on your microcontroller:
`SetEmbeddedConfig()` defines `BufferSlotsCount` to 16 and `BufferSlotSize` to 1024.
(check help at https://github.com/jczic/MicroWebSrv2#mws2-setembeddedconfig)

So, 16x1024 = 16 384 bytes and it's too much for the pool thread.
You can customize these values (see https://github.com/jczic/MicroWebSrv2#mws2-prop) or set the parameter `procStackSize` in the function `StartManaged()` to configure the stack size used by the thread (see https://github.com/jczic/MicroWebSrv2#mws2-startmanaged).

It's ok for you?

**Comment by kenjican** [comment]
Change the parameter : wms._slotsCount = 4 .and then it works great~~ 
Thanks ~

another question: slotCount meas how many sockets opened concurrently?

**Comment by jczic** [comment]
Yes it's for concurrents web requests and websockets too (websockets come from a request).
slotCount = preallocated buffers to works on TCP connections.

**Comment by juanpc13** [comment]
I try this way in esp32 devkit v1:

    from MicroWebSrv2 import *
    
    mws2 = MicroWebSrv2()
    mws2.SetEmbeddedConfig()
    mws2._slotsCount = 4
    mws2.StartManaged()

MWS2-INFO> Server listening on 0.0.0.0:80.
MWS2-INFO> Starts the managed pool to wait for I/O events.
