### ISSUE TITLE
MicroWebSrv2Exception: Cannot load module "PyhtmlTemplate". (v2.0.3)

### ISSUE THREAD

**Issue by iomoio** [jczic/MicroWebSrv2#13]
I get an exception in modClass = getattr(module, modName)
The exception: 'module' object has no attribute 'PyhtmlTemplate'

Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 133, in LoadModule
MicroWebSrv2Exception: Cannot load module "PyhtmlTemplate".
MicroPython v1.11-580-g973f68780 on 2019-11-20; ESP32 module with ESP32

>>> os.listdir()
['boot.py', 'dev-requirements.txt', 'requirements.txt', 'main.py', 'project.pymakr', 'wifiConfig.json', 'wifiConnect.py', 'lib', 'www', 'MicroWebSrv2']
>>> os.listdir('MicroWebSrv2')
['libs', 'mods', 'httpRequest.py', 'httpResponse.py', 'microWebSrv2.py', 'webRoute.py', '__init__.py']
>>> os.listdir('MicroWebSrv2/mods')
['PyhtmlTemplate.py', 'WebSockets.py']

Please help

**Comment by jczic** [comment]
Hi @iomoio and thank you for this issue.
I've checked but I don't understand why the module doesn't have the attribute.
Could you add these 2 lines in `microWebSrv2.py` between lines 126 and 127 as:
```
            module   = __import__(modPath, { }, { }, [modName])
            print('modPath=%s, modName=%s, module=%s' % (modPath, modName, str(module)))
            modClass = getattr(module, modName)
```
Thank you! 👍

**Comment by iomoio** [comment]
modPath=MicroWebSrv2.mods.PyhtmlTemplate, modName=PyhtmlTemplate, module=<module 'MicroWebSrv2.mods.PyhtmlTemplate' from 'MicroWebSrv2/mods/PyhtmlTemplate.py'>

**Comment by iomoio** [comment]
print(dir(module))
['__class__', '__name__', '__file__']

**Comment by jczic** [comment]
Hmm, strange, the main class has not been 
loaded.
You can also try without `modName` on line 126 like:
```
module   = __import__(modPath, { }, { }, [])
```
Maybe this will allow you to load all the content of the module (and the class).

**Comment by iomoio** [comment]
Unfortunately, it's not working too. The same error. (((

**Comment by jczic** [comment]
On your platform, what is the result if you try:
```
x = __import__('json', {}, {}, ['loads'])
y = __import__('os', {}, {}, [])
dir(x)
dir(y)
```

**Comment by iomoio** [comment]
'''
>>> dir(x)
['__class__', '__name__', 'dump', 'dumps', 'load', 'loads']
>>> dir(y)
['__class__', '__name__', 'remove', 'VfsFat', 'VfsLfs2', 'chdir', 'dupterm', 'dupterm_notify', 'getcwd', 'ilistdir', 'listdir', 'mkdir', 'mount', 'rename', 'rmdir', 'stat', 'statvfs', 'umount', 'uname', 'urandom']
'''

**Comment by jczic** [comment]
Ohhh!
So,
```
dir( __import__('MicroWebSrv2.mods.PyhtmlTemplate', {}, {}, []) )
```

**Comment by iomoio** [comment]
```
>>> dir( __import__('MicroWebSrv2.mods.PyhtmlTemplate', {}, {}, []) )
['__class__', '__name__', '__file__']
```

**Comment by jczic** [comment]
Ok, do you load MicroWebSrv2 with:
```
from MicroWebSrv2 import *
```
?

**Comment by iomoio** [comment]
Yes. I try to launch your main.py (from repository).

**Comment by jczic** [comment]
Because when using `import MicroWebSrv2`, `MicroWebSrv2`is a module but with `from MicroWebSrv2 import *`, it's a class loaded from `__init__.py`.
So, on the 2nd case, `MicroWebSrv2.mods.PyhtmlTemplate` exists.
Otherwise, I don't understand where it actually comes from.

**Comment by jczic** [comment]
Hi @iomoio,
I've released a new version (2.0.5) with a fix for your problem with LoadModule.
Commit: https://github.com/jczic/MicroWebSrv2/commit/1b36b348f6f7c975062725910574564b69697653
Is it ok for you?

**Comment by iomoio** [comment]
```
       ---------------------------
       - Python pkg MicroWebSrv2 -
       -      version 2.0.5      -
       -     by JC`zic & HC2     -
       ---------------------------

 + [@WebRoute] GET /test-redir
 + [@WebRoute] GET /test-post (TestPost1/2)
 + [@WebRoute] POST /test-post (TestPost2/2)

Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 134, in LoadModule
MicroWebSrv2Exception: Cannot load module "PyhtmlTemplate".
MicroPython v1.11-580-g973f68780 on 2019-11-20; ESP32 module with ESP32
Type "help()" for more information.
```
Unfortunately, at the moment there is not a single working framework for ESP32. Picoweb cannot be installed on a pure Micropython... Microweb is abandoned... All hope for your project... Thank you for your patience.

**Comment by iomoio** [comment]
```
            modPath  = MicroWebSrv2.__module__.split('microWebSrv2')[0] \
                     + ('mods.%s' % modName)
            try:         
                module   = getattr(__import__(modPath).mods, modName)
            except Exception as e:
                print("First exception:", e)
            try:
                modClass = getattr(module, modName)
            except Exception as e:
                print("Second exception:", e)
            if type(modClass) is not type :
                raise Exception
```

```
First exception: memory allocation failed, allocating 112 byte
Second exception: local variable referenced before assignment
Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 140, in LoadModule
MicroWebSrv2Exception: Cannot load module "PyhtmlTemplate".
```

**Comment by iomoio** [comment]
```
            gc.collect()
            modPath  = MicroWebSrv2.__module__.split('microWebSrv2')[0] \
                     + ('mods.%s' % modName)
            try:         
                module   = getattr(__import__(modPath).mods, modName)
            except Exception as e:
                print("First exception:", e)
                print("Mem:", gc.mem_free())
```
```
First exception: memory allocation failed, allocating 506 bytes
Mem: 4832
```
I assume the problem is in the mods files... (((
https://forum.micropython.org/viewtopic.php?t=4997

**Comment by jczic** [comment]
Okay...! I see.
You don't have an ESP32 with 4Mo RAM...
Effectively, you can copy the package in the `frozen` directory and compile the firmware yourself...
But with 4832, it's very very light!
