### ISSUE TITLE
MicroWebSrv2.NotFoundURL no effect on ESP32

### ISSUE THREAD

**Issue by Walkline80** [jczic/MicroWebSrv2#15]
fake code:

```python
from MicroWebSrv2 import *

server = MicroWebSrv2()
server.RootPath = "web"
server.NotFoundURL = "/"
server.StartManaged()

while server.IsRunning:
    sleep(1)
```

In ESP32, client connected to server, rqeust root path, server cause 307 redirect, in this time, the default file (index.html etc) is not loaded, and then client will request root path again and server respond a 307 redirect, and loop again, and again....

I'm using MicroPython official lastest firmware of ESP32.

**Comment by jczic** [comment]
Hi @Walkline80 and thank you.
Do you have the last version 2.0.5 (released in the last few hours)?
I've fixed a problem concerning physical path method on some platforms.
