### ISSUE TITLE
WebSocket module cannot receive more than 126 chars

### ISSUE THREAD

**Issue by Walkline80** [jczic/MicroWebSrv2#19]
If ws client send a string which length more than 126, the connection will be closed, is there any solution to avoid this problem?

**Comment by jczic** [comment]
Hello @Walkline80,
Exactly 👍 this is a **function scope** problem with `length` variable.
I've fixed this bug : 4da4389898c29072ef9e127608dcce5399bdb64f :)
Thank you!
