### ISSUE TITLE
No module named  '_thread'

### ISSUE THREAD

**Issue by Thylekk** [jczic/MicroWebSrv2#20]
Hello, 

I have Pyboard and TILE SENSA sensor (temperature&humidity) and I would love to interpret values from the sensor to my own webserver and make sort of my own meteostation which I can access from my laptop or smarth phone.

The problem is when I try to start the "main.py" (renamed to "start.py" in my case). The console pops: 
ImportError: no module named '_thread'

I tried googling this proble, but I found no answer to my particular problem.
Only thing that cause this issue is Micropython version, but since this is also for Pyboards, it should not be the problem.

Thnaks for any help or answers in advance :]

![image](https://user-images.githubusercontent.com/59178976/71375235-d4f39000-25bd-11ea-9025-82470019bb0d.png)

**Comment by Thylekk** [comment]
I found this:

https://forum.micropython.org/viewtopic.php?f=20&t=7305

but I dont really understand how this works

**Comment by jczic** [comment]
Hello @Thylekk,
Yes, in some micropython firmware, `_thread` is not present by default...
You should to compile the firmware with threads support if it's possible.
