### ISSUE TITLE
How to run (in proper way) second function in parallel?

### ISSUE THREAD

**Issue by mvincm** [jczic/MicroWebSrv2#23]
Hello,

Good pice of code! Big up! Thanks for your work.

I have one question. I'm looking for a proper method to run a function in parallel to web server. I would like to check every 30 seconds my temperature and send values to MQTT server. This should be independent of normal web server activity. What is the best way to do this using MicroWebSev2?

Best regards,
MvincM

**Comment by jczic** [comment]
Hello @mvincm,
This is not a problem, MicroWebSrv2 runs in threads, so you can use a simple alarm (timer) or a dedicated thread.
It's ok for you?

**Comment by mvincm** [comment]
Hello,

Timer will be good to do this simple job. Should I run it before main loop "try" or in "try"?

P.S.
I'm not familiar with threads in Micropython so Timer looks better for me.

MvincM

**Comment by jczic** [comment]
You can initialize a timer before but that's not the question because it will call a callback function from another thread.
