### ISSUE TITLE
Show real-time data

### ISSUE THREAD

**Issue by AHardReset** [jczic/MicroWebSrv2#24]
Hi! Thanks for this micropython tool, I have worked with it and I'm learning a lot!

I need some help, can you send me a example of how show real-time data in a propely way?
I have an analog sensor in my esp8266, I would like to see the data in a page.

Greetings! and thanks in advance

**Comment by jczic** [comment]
Hello @AHardReset 
You can check the "chat" example in demo to working with "real-time" data :)
WebSockets are recommended to do that!

**Comment by AHardReset** [comment]
Ok thanks!
