### ISSUE TITLE
pyhtml tot being served in lopy

### ISSUE THREAD

**Issue by note5** [jczic/MicroWebSrv2#25]
I have installed the server on lopy But the files apart from index.html are not being served, I get a 404, even the png image is not being loaded (404 from the network tab of chrome dev tools. Is it a file format issue with lopy, is there a fix for this?

**Comment by jczic** [comment]
Hello,
MicroWebSrv2 works on Pycom LoPy.
Could you publish the debug-logs please?
Do you have checked your files system by FTP on your LoPy?

**Comment by note5** [comment]
This is what I get  when I click the pdf link
[image: image.png]

this is the files I see when using ftp
[image: image.png]
I have only cloned the repo and  added boot.py and wifi connection code in
the main.py file

**Comment by note5** [comment]
This is my project file

**Comment by jczic** [comment]
Hello @note5 and sorry for the late.
Your messages are not visible on github :
https://github.com/jczic/MicroWebSrv2/issues/25
(Don't forget to publish the term/repl logs).

**Comment by theBASTI0N** [comment]
Hey,

I had this same issue on a WiPy if you are using pymakr to upload your files, you will need to go to Pymakr Global Settings and add ico and pyhtml files to "Upload File Types"

**Comment by jczic** [comment]
@theBASTI0N 👍

**Comment by note5** [comment]
thank you it, has really saved me
