### ISSUE TITLE
how to prevent escaping HTML tags in GlobalVars?

### ISSUE THREAD

**Issue by bennyzen** [jczic/MicroWebSrv2#27]
using `PyhtmlTemplate`, if I do something like this:
```
pyhtmlTemplateMod.SetGlobalVar('Header', '<html><head><title>markup as string</title></head><body>')
```

all my html tags are escaped. is there a way to prevent that? sorry if this is a silly question.

**Comment by jczic** [comment]
Hello @bennyzen,
`SetGlobalVar` doesn't escapes the variables but if you use `{{ MyVar }}`, the rendered will be escaped. This is normal.
If you want to put directly html code, you should use a javascript like `myElement.innerHTML = "{{ MyVar }}";`

**Comment by bennyzen** [comment]
Thank you for your quick reply.
I'm trying to preload some HTML markup into GlobalVars like this:
```
tmpl_header = open('/www/tmpl/header.html','r').read()
pyhtmlTemplateMod.SetGlobalVar('Header', tmpl_header)
```
Later on in my `layout.pyhtml` I'm trying to reuse these template partials, doing something trivial like:
```
{{ Header }}
  Something between
{{ Footer }}
```
But unfortunately all markup in `Header` and `Footer` is escaped, resulting in something like this:
```
&apos;&lt;html&gt;&lt;head&gt;&lt;title&gt;Test as string&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&apos;
  Something between
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
```
Maybe I'm just missing the right syntax to prevent the template engine from escaping the tags?

**Comment by bennyzen** [comment]
As suggestion for a possible feature: Why not implement a rawHTML mode using three curly brackets?

Maybe something like this `{{{ Header }}}`, for raw and unsescaped HTML. If I remember right, vue.js does it the same way.

**Comment by jczic** [comment]
Okay, so if you want to directly use unescaped HTML from variables you can set :
`MicroWebSrv2.HTMLEscape = None`
I'll see to add a new mechanism to have both methods.

**Comment by jczic** [comment]
New commit: https://github.com/jczic/MicroWebSrv2/commit/68a7ac598f36894ec5aab3768f20b03eb971077f
Now, you can use `print('<u>test</u>')` from your python code in pyhtml files to directly rendering unescaped string.
(See `test.pyhtml` example) :)

**Comment by bennyzen** [comment]
@jczic Thank you so much for the fast implementation! 

Just tested it and it works great. Now `PyhtmlTemplate` has support for template partials. 

Keep up your good work.

**Comment by jczic** [comment]
👍
