### ISSUE TITLE
Webroutes handler and .pyhtml files are not working on lopy4 with Pysense 

### ISSUE THREAD

**Issue by aqieez** [jczic/MicroWebSrv2#3]
I am using lopy4 with Pysense. I have copied all files of project into lopy4. After connecting with lopy4 wifi, I can only access index.htlm and wstest.html pages are not working. I am always getting error loclhost refused to connect. while testing this project on linux and running it through python main.py then it's working fine. But why it's not working on microcontroller lopy4 i have already updated lopy4 to latest version.

**Comment by jczic** [comment]
Hello, what are the logs you can see in the LoPy4 terminal?
Did you try with http://192.168.4.1/..... ?

**Comment by aqieez** [comment]
hi there, thanks for the reply. I can't see any logs in the LoPy4 terminal. what do you mean if I tried with http://192.168.4.1  Should I change the default port and address like this mws2.BindAddress = ('192.168.0.1', 8080) or what? on boot I can see Server listening on 0.0.0.0:80 in LoPy terminal

**Comment by jczic** [comment]
Leave 0.0.0.0 because this is to listen on all network interfaces/IPs.
But if you don't see a log in your terminal, then you can't connect at all.
How do you connect in http?
The LoPy address is 192.168.4.1 by default, so once you are connected to your LoPy via WiFi, try http://192.168.4.1/

**Comment by aqieez** [comment]
Yes I'm connecting to LoPy via LoPy wifi then i am accessing http through http://localhost. When i try 192.168.4.1. I'm getting error like server took to long to respond. But with hocalhost i am able to call index.html and other html file but i can't call pyhtml template and router

**Comment by jczic** [comment]
So, if you have others pages, you have logs...
Could you give me all logs :)

**Comment by aqieez** [comment]
@jczic sorry for the late response. logs from where? browser? or atom? atom won't show anything and I am not sure for what logs you are asking for

**Comment by jczic** [comment]
👍
