### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by GitHubForTester** [jczic/MicroWebSrv2#34]
Hello, 

Thank you for your good documented package. I try to run it on a ESP32 with only two other packages, but I get a memory issue for importing `HttpResponse`

The complete message seems like this:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "/lib/MicroWebSrv2/__init__.py", line 18, in <module>
  File "/lib/MicroWebSrv2/microWebSrv2.py", line 8, in <module>
  File "/lib/MicroWebSrv2/httpRequest.py", line 8, in <module>
MemoryError: memory allocation failed, allocating 136 bytes
```
Have you an idea? It's every run 136 bytes
In another post I have red, dividing the file in to is possible, but I don't know, how I can divide a class...
Thank you very much!

**Comment by jczic** [comment]
Hello @GitHubForTester,
Ok, I think that you have an ESP32 without extended SPIRAM.
MicroWebSrv2 code is too large for import (and eval) it on the fly.
You can use an ESP32 with 4MB of SPIRAM or you can also embed it as a micropython library before compiling the firmware yourself (the module will be already compiled in your ESP32 and the memory usage will be less).

**Comment by GitHubForTester** [comment]
Hello @jczic,
thank you for your fast response.

This can be possible. Have you a link with a instruction to embed it as a micropython library? I have no idea, how it's possible.

Actually I have no ESP32 with 4MB SPIRAM, at that term I must pay attention while order? Simple 4MB SPIRAM?

Thank you very much!

**Comment by GitHubForTester** [comment]
Ok thank you, I think it's a little bit overkill for my application, but thank you very much!

**Comment by tionebrr** [comment]
If anyone wants to compile custom Micropython firmware without messing their already installed and working ESP-IDF build environment, I made a docker container with build tools for the ESP32.
https://hub.docker.com/r/tionebrr/micropython-tools-esp32
