### ISSUE TITLE
Serving static files?

### ISSUE THREAD

**Issue by William04A** [jczic/MicroWebSrv2#37]
I have been trying to get my instance of MWS2 to serve static files, but it doesn't work as I expect.
I have set the mws2.RootPath = "/flash/server/www".
The file contents of this directory include several files. I tried with the exact filename both directly after 192.168.4.1 (like so: 192.168.4.1/figure.svg) and also 192.168.4.1/static/figure.svg (I was unsure which one was right).

What can be wrong here?

**Comment by William04A** [comment]
I get 404.

**Comment by William04A** [comment]
Also, I have noticed that a dot (.) can interrupt the string placeholder (eg. "<file>"). I don't know if that is expected or not.

**Comment by YveIce** [comment]
Try it with out the first slash, and "/flash":
```
mws2 = MicroWebSrv2()
mws2.RootPath = 'server/www'
```

that's working for  me on an ESP32, where "server" is a folder inside the "root" of the VFS (the same folder where boot.py and main.py goes, to make it clear).

**Comment by William04A** [comment]
Alright. Something else I'm wondering is how the server treats requests to static files. Do I have to do [host url]/static/filename.format, or is the format just [host url]/filename.format?

**Comment by YveIce** [comment]
The Server will first walk thru all your **@WebRoute** declarations, then he will look up for existing files based on the **RootPath** and finally he goes to **NotFoundURL**.

Example, thats your VFS:
```
\.
|-- boot.py
|-- main.py
|-- [www]
   |--index.htm
   |--[css]
         |--style.css
```
Your request **GET /index.htm**
with **mws2.RootPath = ''** => not found
with **mws2.RootPath = 'www' => **found**

Your request **GET /style.css**
with **mws2.RootPath = ''** => not found
with **mws2.RootPath = 'www'** => not found
with **mws2.RootPath = 'www/css'** => **found**

Your request **GET /css/style.css**
with **mws2.RootPath = ''** => not found
with **mws2.RootPath = 'www'** => **found**
with **mws2.RootPath = 'www/css'** => not found

But pay attention if do something like `@WebRoute(GET, '/index.htm')`, then this will totally ignore your file. And having many files in one folder, slows the system down. So it should be a good idea to split things in different folders.

**Comment by William04A** [comment]
Thank you! I will try to get things up working based on your description and get back with the result.

**Comment by William04A** [comment]
I'm sorry, but my MWS2 instance doesn't still behave as expected.

My working directory (os.getcwd()) is /flash/server.
I tried with no root path, and with the rootpath server/ as well as server/www.

With no root path or the root path "server/", I attempted with visiting the URL /internal_step2.html, which is located in the /server folder. I also attempted with the URL /www/access-point.svg, which didn't work, but the file "access-point.svg" indeed exists in the directory "server/www". With the root path "server/www", visiting /access-point.svg also didn't work. With "didn't work" or "gave an error", I mean that I get 404.

I'm trying to find some kind of obvious mistake I made somewhere, but I can't find it.

**Comment by YveIce** [comment]
What Firmware are u using?
I use: https://micropython.org/resources/firmware/esp32spiram-idf3-20191220-v1.12.bin on ESP-32 with 4M Flash

Try to make a fresh clean install. 
Then connect to the build in shell and try:
```
>>> print (os.getcwd())
My Result: /
>>> print(os.listdir())
My Result: 
['boot.py']
```

Upload the two folders "MicroWebSrv2" and "www" from this git in the same folder where "boot.py" is. Thonny (https://thonny.org/) is your friend.
Add and edit this lines to the top of the "main.py" from this git:
```
import network
nic = network.WLAN(network.STA_IF)
nic.active(True)
nic.connect('YOURWIFI_SSID', 'YOURWIFI_PWD')
```
Upload it to the root folder where "boot.py" is.

Now reset your device by the hardware reset-key (or how it's done on your device).
Wait until you find it on your wifi, and check if you get the demopage on:
http://192.0.1.2/index.html (where 192.0.1.2 is the ip of your esp32).

If this is not working, then you do something wrong or your device is magic. ;-)

**Comment by William04A** [comment]
> If this is not working, then you do something wrong or your device is magic. ;-)

It's a Pycom... 😞 

No, but seriously, thank you so much for those detailed instructions. I will try them out tomorrow and get back. Hopefully, it can be solved.

**Comment by YveIce** [comment]
Ok, then it is a Magic Device. ;-) 
They use a custom version of micropython. (https://github.com/pycom/pycom-micropython-sigfox)
MAYBE there is something different in the handling of the filesystem. 

So best would be, flash proper micropython firmware as posted above should work on WiPy 3.0 device. You can use esptool.py or thonny build-in tool for this. Then your device will work and behave like a normal ESP-32 with some spare-parts soldered around :-)
Then just follow my gui above. 
Later you can switch back to the pycon firmware, if u still like to. :-)

**Comment by William04A** [comment]
The thing is that I'm working on a production application, and therefore it would be best to stick to Pycom's firmware. I know that they use a custom version, and honestly, the experience working with Pycom devices is not entirely smooth. MWS2 is claimed in the documentation to work on Pycom, and it is an amazing piece of software.

**Comment by YveIce** [comment]
If u wanne stick with the pycon universe, the last thing you can try:
put in every folder a simple html-file. But give each file a different name. Like
a.htm in root-folder, b.htm in /www/ and so on. Then reboot device and open the ip on your browser and try each filename (http://x.x.x.x/a.htm and so on) until you succeed. 
Then you know where the current root path is. Trial & Error. ;-) 

Also i don't know what "production application" means to you, but i wouldn't use a peace of software when i'm not 100% comfortable with it. :-)

**Comment by William04A** [comment]
This is almost embarrassing...

Pycom has a thing which is a trap I have fallen in once before. You need to specify a list of filetypes that should be updated to the device. This list included .HTML, but not .svg and .png, which were two of the files I tested with. 

Sorry for not realizing this any sooner, but the steps you mentioned are great troubleshooting steps for every problem. Thank you! Now I can start to play around with MWS2 for real.

**Comment by YveIce** [comment]
Glade we figure it out. Happy coding! ;-)
