### ISSUE TITLE
403 when trying to load .pyhtml template?

### ISSUE THREAD

**Issue by William04A** [jczic/MicroWebSrv2#43]
I know I have been posting about silly path errors here before. It has finally been solved. But there is one thing I can't get to work. I have to .pyhtml-templates, and when I try to load these, I just get a "403 forbidden" error with the kind of strange message "Request forbidden -- authorization will not help.". Authorization is not the option, so what do I do?

Template names:
about.pyhtml and network.pythml
Request URLs:
192.168.4.1/templates/about.pyhtml (same response as mentioned above)
192.168.4.1/templates/network.pyhtml (same response as mentioned above)
Rootpath:
/flash/server/www
The templates are in the "templates" folder, a subfolder of www.

**Comment by William04A** [comment]
I only needed variables in the HTML file, so I had to do a non-optimal but working solution using format() instead, as I haven't gotten a response yet. I guess I will close this (for my case), although I technically still have the issue.

**Comment by glowingkitty** [comment]
Had the same issue. Seems it was an error while processing some variables inside the .pyhtml. After removing them and starting with a clean html file instead - it worked.
