### ISSUE TITLE
Websocket packets are buffered and sent per seconds instead of real time

### ISSUE THREAD

**Issue by zzfjean** [jczic/MicroWebSrv2#57]
Hi @jczic - great work on this web server, excellent quality docs as well. 

I've implemented the server on a Pycom G01 (esp32) and it seems to be running well. I also run a websocket for a specific webUI page displaying real-time data to a driver using gps read-outs. 

I need the websocket data to update every 200ms (5hz) and in my code this is easily achievable - however the server seems to be buffering the data and sending as batches. 

I've wiresharked it to make sure its not on the client side - and in below image you can see the bundles of packets being sent together every 1 second. 

![image](https://user-images.githubusercontent.com/47771147/104120828-8f029900-5385-11eb-9db1-015ee054410d.png)

Implementation code - pretty much the example code. 

     wsMod = MicroWebSrv2.LoadModule('WebSockets')
      wsMod.OnWebSocketAccepted = OnWebSocketAccepted
      # Instanciates the MicroWebSrv2 class,
      mws2 = MicroWebSrv2()
      mws2.RootPath = '/flash/'
      mws2.BindAddress = ('192.168.4.1', 5000)
      # For embedded MicroPython, use a very light configuration,
      mws2.SetEmbeddedConfig()
      
      # All pages not found will be redirected to the home '/',
      mws2.NotFoundURL = '/'
      mws2.StartManaged(parllProcCount=1,procStackSize = 10*1024)

Could really appreciate your thoughts on this. 

I've managed to accidentality get it to send data in real time a couple of times while trying to fix the issue - by setting parllProcCount =2 but this causes other instability issues and core dumps.

**Comment by jczic** [comment]
Hello @zzfjean,
I've fixed this delay problem with multiple TCP writing in XAsyncSockets lib.
(commit https://github.com/jczic/MicroWebSrv2/commit/42d1bde3d635722dc8fc68834e9e8df8dea9ccbb)

**Comment by jczic** [comment]
@zzfjean Does this work better for you?

**Comment by zzfjean** [comment]
@jczic awesome work with a quick response - I'll test this first thing tomorrow!

**Comment by zzfjean** [comment]
@jczic  i can confirm your change fixed this issue - great work and thank you for the quick resolution!

Screenshot below from wireshark now shows around 5hz update rate nicely distributed. 

![image](https://user-images.githubusercontent.com/47771147/104526092-97d0c480-563c-11eb-9a5c-dc7cce0e23a1.png)
