### ISSUE TITLE
filename error by [ ResolvePhysicalPath ]

### ISSUE THREAD

**Issue by elSayaka** [jczic/MicroWebSrv2#6]
Hello.
At first, I am no good at English,
So this Issue may contain some grammatical mistakes. Sorry.

I try to use MicroWebSrv2 to create a simple web system.
Today,  I found an error in my program.
All files in root-directory (mws2.RootPath) can't find. and return 403.

The same code worked success yesterday, But today it doesn't work.

I found the error occurred in `httpRequest.py`

```python
    def _processRequest(self) :
        if not self._processRequestModules() :
            if not self.IsUpgrade :
                if not self._processRequestRoutes() :
                    if self._method == 'GET' or self._method == 'HEAD' :
                        filename = self._mws2.ResolvePhysicalPath(self._path)
                        # if filename[-1] == '/':
                        #     filename = filename[:-1]
                        if filename :
                            ct = self._mws2.GetMimeTypeFromFilename(filename)
                            if ct :
                                self._response.AllowCaching = True
                                self._response.ContentType  = ct
                                self._response.ReturnFile(filename)
                            else :
                                self._response.ReturnForbidden()
                        else :
                            self._response.ReturnNotFound()
                    else :
                        self._response.ReturnMethodNotAllowed()
            else :
                self._response.ReturnNotImplemented()
```

`filename = self._mws2.ResolvePhysicalPath(self._path)`
return a filename end with `/`
such as `/var/www/html/test.html/`

but if filename end with `/` GetMimeTypeFromFilename and ReturnFile can't work.

when I add this two-line to remove `/`
```python
if filename[-1] == '/':
    filename = filename[:-1]
```
webserver worked success.

would you know some more details about this error?

**Comment by jczic** [comment]
Hi,
Do you have the updated the last version of the repository ?
The ResolvePhysicalPath function has been changed recently.
Normally, that's works well to resolve physical path of directories, index files and other pages.
Otherwise, if you have the last version, it's very strange and I must check why the function os.stat() works with a file path terminated by '/'.

**Comment by elSayaka** [comment]
I updated to the last version and try again.
But the error already exists.

And I found only when I run the script using `sudo`, this error will happen.

I add test code to httpRequest.py

```python
filename = self._mws2.ResolvePhysicalPath(self._path)
print('----------------')
print(filename)
print('----------------')
```
When I the run script using `sudo`.

```
----------------
/Users/el.s/Desktop/el.S/Moca_v2/src/Core/config/../../../www/404.html/
----------------
----------------
/Users/el.s/Desktop/el.S/Moca_v2/src/Core/config/../../../www/favicon.ico/
----------------
```

When I run the script without `sudo`.

```
----------------
/Users/el.s/Desktop/el.S/Moca_v2/src/Core/config/../../../www/404.html
----------------
----------------
/Users/el.s/Desktop/el.S/Moca_v2/src/Core/config/../../../www/favicon.ico
----------------
``

Only when I run the script using `sudo`, the filename ends with `/`

**Comment by elSayaka** [comment]
And I try to run the main.py that in your repository.
same error happened.

I use macOS Catalina and python 3.7 .

**Comment by elSayaka** [comment]
I try to run the script using `sudo` and without `sudo`, on centos7.
Both types worked successfully.

this error may be only happening on the macOS.

**Comment by jczic** [comment]
Ok, that's fixed :)

**Comment by jczic** [comment]
Oh no, just an error again on macos without sudo... an instant plz

**Comment by elSayaka** [comment]
Nice!
Thank you very much! :)
